# Generated by Django 2.0.6 on 2018-10-21 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0004_auto_20181021_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_ride',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='endLoc',
            field=models.CharField(default='IND', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='startLoc',
            field=models.CharField(default='Purdue', max_length=100),
        ),
    ]
