# Generated by Django 2.0 on 2018-10-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('startLoc', models.CharField(max_length=100)),
                ('endLoc', models.CharField(max_length=100)),
                ('dateOfride', models.DateTimeField(blank=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
