# Generated by Django 2.0 on 2018-10-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20181020_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='seats',
            field=models.IntegerField(default=1),
        ),
    ]
